name: nanoid2
version: 2.0.1
description: A tiny, secure, URL-friendly, unique string ID generator, nanoid with a pure Dart API.
repository: https://github.com/passsy/nanoid

environment:
  sdk: ">=2.12.0 <4.0.0"

dev_dependencies:
  lint: '>=1.0.0 <3.0.0'
  test: ^1.16.4

topics:
  - identifier
  - uuid
  - id
  - random
