name: nanoid2
version: 2.0.0
description: A tiny, secure, URL-friendly, unique string ID generator. Dart implementation of nanoid
homepage: https://github.com/pd4d10/nanoid-dart

environment:
  sdk: ">=2.12.0 <4.0.0"

dev_dependencies:
  lint: '>=1.0.0 <3.0.0'
  test: ^1.16.4
