name: Dart CI

on: [push, pull_request]

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: ["2.12", "2.19", "3.0", "beta"]

    container:
      image: dart:${{ matrix.version }}

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: dart pub get
      - name: Run tests
        run: dart pub run test

  format:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    container:
      image: dart:stable

    steps:
      - uses: actions/checkout@v2
      - name: Format
        run: dart format --set-exit-if-changed --fix .
